image: docker:stable

stages:
- build
- deploy-homolog
- deploy-production

build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/mateusrovedaa/gcs-controle-financeiro .
    - docker push $CI_REGISTRY/mateusrovedaa/gcs-controle-financeiro

deploy-homolog:
  stage: deploy-homolog
  dependencies:
    - build
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client curl -y )'
    - eval `ssh-agent -s`
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - curl ipinfo.io/ip
    - ping 177.44.248.65
    - ssh-keyscan -i ~/.ssh/id_rsa 177.44.248.65 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - ssh -i ~/.ssh/id_rsa -T -p22 univates@177.44.248.65 -v
    - ssh -i ~/.ssh/id_rsa -v univates@177.44.248.65 ' ./home/univates/homologacao/update.sh'

deploy-production:
  image: ubuntu
  stage: deploy-production
  dependencies:
    - build
    - deploy-homolog
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}"
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -t -p22 univates@177.44.248.65
    - ssh univates@177.44.248.65 ' ./home/univates/producao/update.sh'
  when: manual
