image: docker:stable

stages:
- build
- test
- deploy

build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/mateusrovedaa/gcs-controle-financeiro .

tests:
  stage: test
  script:
    - cp .env.example .env
    - php artisan key:generate
    - ./vendor/bin/phpunit
  dependencies:
  - build

deploy:
  stage: deploy
  script:
    - docker push  $CI_REGISTRY/mateusrovedaa/gcs-controle-financeiro
  dependencies:
    - tests

