image: docker:stable

stages:
- build
- deploy-homolog
- deploy-production

build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/mateusrovedaa/gcs-controle-financeiro .
    - docker push $CI_REGISTRY/mateusrovedaa/gcs-controle-financeiro

deploy-homolog:
  stage: deploy-homolog
  dependencies:
  - build
  before_script:
  - eval $(ssh-agent -s)
  - bash -c "ssh-add <(echo '$SSH_PRIVATE_KEY')"
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh univates@177.44.248.65 ' ./home/univates/homologacao/update.sh'
  when: manual

deploy-production:
  stage: deploy-production
  dependencies:
  - build
  - deploy-homolog
  before_script:
  - eval $(ssh-agent -s)
  - bash -c "ssh-add <(echo '$SSH_PRIVATE_KEY')"
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh univates@177.44.248.65 ' ./home/univates/producao/update.sh'
  when: manual
